### ISSUE TITLE
[BUG] inter_sample_shift cannot always be found for phase shift

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/swc_ephys#29]
For some reason, the spikeinterface-generated `inter_sample_shift` property is not always found on SpikeGLX files. This leads phase-shifting to fail with the error

```
Traceback (most recent call last):
  File "/ceph/neuroinformatics/neuroinformatics/scratch/jziminski/ephys/code/swc_ephys/swc_ephys/examples/./example_full_pipeline.py", line 18, in <module>
    run_full_pipeline(
  File "/ceph/neuroinformatics/neuroinformatics/scratch/jziminski/ephys/code/swc_ephys/swc_ephys/pipeline/full_pipeline.py", line 93, in run_full_pipeline
    data = preprocess(data, pp_steps, verbose)
  File "/ceph/neuroinformatics/neuroinformatics/scratch/jziminski/ephys/code/swc_ephys/swc_ephys/pipeline/preprocess.py", line 55, in preprocess
    perform_preprocessing_step(
  File "/ceph/neuroinformatics/neuroinformatics/scratch/jziminski/ephys/code/swc_ephys/swc_ephys/pipeline/preprocess.py", line 179, in perform_preprocessing_step
    data[new_name] = pp_funcs[pp_name](last_pp_step_output, **pp_options)
  File "/nfs/nhome/live/jziminski/.conda/envs/swc_ephys/lib/python3.10/site-packages/spikeinterface/core/core_tools.py", line 28, in reader_func
    return source_class(*args, **kwargs)
  File "/nfs/nhome/live/jziminski/.conda/envs/swc_ephys/lib/python3.10/site-packages/spikeinterface/preprocessing/phase_shift.py", line 42, in __init__
    assert "inter_sample_shift" in recording.get_property_keys(), "'inter_sample_shift' is not a property!"
AssertionError: 'inter_sample_shift' is not a property!
```

For example this is currently occurring with `run_full_pipeline.py`:

```
base_path = Path(
    r"/ceph/neuroinformatics/neuroinformatics/scratch/jziminski/ephys/test_data/steve_multi_run/1119617"
    r"/time-mid"
)
sub_name = "1119617"  # "cut_same_name"
run_names = ["1119617_LSE1_shank12",
             "1119617_posttest1_shank12",
             "1119617_pretest1_shank12"]

config_name = "test"
sorter = "kilosort2_5"
```

**Comment by JoeZiminski** [comment]
I am 99% sure this was due to an issue in exporting cut-down versions of test files, and is not observed for 'real' data. Will re-open if this comes up again.
