### ISSUE TITLE
[BUG] on windows need pip install pypiwin32

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/swc_ephys#9]
1) on windows need pip install pypiwin32 for cuda 
2) now running with `pwd` error (is a linux thing, stacktrace below

```
Starting kilosort2_5 sorting...
Traceback (most recent call last):
  File "C:\Users\Joe\work\git-repos\swc_ephys\swc_ephys\examples\example_full_pipeline.py", line 13, in <module>
    run_full_pipeline(
  File "C:\Users\Joe\work\git-repos\swc_ephys\swc_ephys\pipeline\full_pipeline.py", line 60, in run_full_pipeline
    run_sorting(data, sorter, sorter_options, use_existing_preprocessed_file, verbose=verbose)
  File "C:\Users\Joe\work\git-repos\swc_ephys\swc_ephys\pipeline\sort.py", line 67, in run_sorting
    ss.run_sorter(
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spikeinterface\sorters\runsorter.py", line 138, in run_sorter
    return run_sorter_container(
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spikeinterface\sorters\runsorter.py", line 476, in run_sorter_container
    container_client = ContainerClient(mode, container_image, volumes, py_user_base_unix, extra_kwargs)
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spikeinterface\sorters\runsorter.py", line 262, in __init__
    from spython.main import Client
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spython\main\__init__.py", line 77, in <module>
    Client = get_client()
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spython\main\__init__.py", line 19, in get_client
    from .base import Client as client
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spython\main\base\__init__.py", line 9, in <module>
    from spython.utils import check_install, get_singularity_version
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spython\utils\__init__.py", line 3, in <module>
    from .terminal import (
  File "C:\Users\Joe\miniconda3\envs\swc_ephys\lib\site-packages\spython\utils\terminal.py", line 12, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

```

**Comment by JoeZiminski** [comment]
I  think this is due to singularity not working on Windows moved to #21
